security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        in_database:
            entity:
                class: App\Entity\User
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            provider: in_database

            guard:
                authenticators:
                    - App\Security\UsersAuthenticator


            logout:
                path: app_logout
                target: visiteur

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: admin_, roles: ROLE_ADMIN }
        - { path: client_, roles: ROLE_USER }
        - { path: coach_, roles: ROLE_COACH }

    role_hierarchy:
        ROLE_COACH: ROLE_USER
        ROLE_ADMIN: ROLE_COACH




